/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as UiRouteRouteImport } from './routes/ui/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiEventsRouteImport } from './routes/ui/events'
import { Route as UpdateAppNameRouteRouteImport } from './routes/update/$appName/route'
import { Route as UiAppIdRouteRouteImport } from './routes/ui/$appId/route'
import { Route as UpdateAppNameStatusRouteImport } from './routes/update/$appName/status'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRouteRoute = UiRouteRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiEventsRoute = UiEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => UiRouteRoute,
} as any)
const UpdateAppNameRouteRoute = UpdateAppNameRouteRouteImport.update({
  id: '/update/$appName',
  path: '/update/$appName',
  getParentRoute: () => rootRouteImport,
} as any)
const UiAppIdRouteRoute = UiAppIdRouteRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => UiRouteRoute,
} as any)
const UpdateAppNameStatusRoute = UpdateAppNameStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => UpdateAppNameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/login': typeof LoginRoute
  '/ui/$appId': typeof UiAppIdRouteRoute
  '/update/$appName': typeof UpdateAppNameRouteRouteWithChildren
  '/ui/events': typeof UiEventsRoute
  '/update/$appName/status': typeof UpdateAppNameStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui': typeof UiRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/login': typeof LoginRoute
  '/ui/$appId': typeof UiAppIdRouteRoute
  '/update/$appName': typeof UpdateAppNameRouteRouteWithChildren
  '/ui/events': typeof UiEventsRoute
  '/update/$appName/status': typeof UpdateAppNameStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/login': typeof LoginRoute
  '/ui/$appId': typeof UiAppIdRouteRoute
  '/update/$appName': typeof UpdateAppNameRouteRouteWithChildren
  '/ui/events': typeof UiEventsRoute
  '/update/$appName/status': typeof UpdateAppNameStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/apps'
    | '/login'
    | '/ui/$appId'
    | '/update/$appName'
    | '/ui/events'
    | '/update/$appName/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui'
    | '/apps'
    | '/login'
    | '/ui/$appId'
    | '/update/$appName'
    | '/ui/events'
    | '/update/$appName/status'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/apps'
    | '/login'
    | '/ui/$appId'
    | '/update/$appName'
    | '/ui/events'
    | '/update/$appName/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRouteRoute: typeof UiRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  LoginRoute: typeof LoginRoute
  UpdateAppNameRouteRoute: typeof UpdateAppNameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/events': {
      id: '/ui/events'
      path: '/events'
      fullPath: '/ui/events'
      preLoaderRoute: typeof UiEventsRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/update/$appName': {
      id: '/update/$appName'
      path: '/update/$appName'
      fullPath: '/update/$appName'
      preLoaderRoute: typeof UpdateAppNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/$appId': {
      id: '/ui/$appId'
      path: '/$appId'
      fullPath: '/ui/$appId'
      preLoaderRoute: typeof UiAppIdRouteRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/update/$appName/status': {
      id: '/update/$appName/status'
      path: '/status'
      fullPath: '/update/$appName/status'
      preLoaderRoute: typeof UpdateAppNameStatusRouteImport
      parentRoute: typeof UpdateAppNameRouteRoute
    }
  }
}

interface UiRouteRouteChildren {
  UiAppIdRouteRoute: typeof UiAppIdRouteRoute
  UiEventsRoute: typeof UiEventsRoute
}

const UiRouteRouteChildren: UiRouteRouteChildren = {
  UiAppIdRouteRoute: UiAppIdRouteRoute,
  UiEventsRoute: UiEventsRoute,
}

const UiRouteRouteWithChildren =
  UiRouteRoute._addFileChildren(UiRouteRouteChildren)

interface UpdateAppNameRouteRouteChildren {
  UpdateAppNameStatusRoute: typeof UpdateAppNameStatusRoute
}

const UpdateAppNameRouteRouteChildren: UpdateAppNameRouteRouteChildren = {
  UpdateAppNameStatusRoute: UpdateAppNameStatusRoute,
}

const UpdateAppNameRouteRouteWithChildren =
  UpdateAppNameRouteRoute._addFileChildren(UpdateAppNameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRouteRoute: UiRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  LoginRoute: LoginRoute,
  UpdateAppNameRouteRoute: UpdateAppNameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
