name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.20.3"
      - name: Setup token
        run: |
          npm config set access=public
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      # Node
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install deps
        run: |
          npm install -g pnpm@8.15.8
          pnpm install

      - name: Build
        working-directory: packages/cli
        run: |
          pnpm build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        working-directory: packages/cli/dist
        run: |
          npm version 0.1.${{ github.run_number }} --no-git-tag-version
          npm publish
